export const careplans = [
  {
    name_of_prebuilt_care_plan: "II/36/2",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 36,
    number_of_monts: 4,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 4,
    number_of_weeks_at_2xweek: 12,
    number_of_weeks_at_1xweek: 0,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 3,
    progres_x_ray: 1,
    denne_roll: 0,
    foam_roller: 0,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "II/36/2x",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 36,
    number_of_monts: 3,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 12,
    number_of_weeks_at_2xweek: 0,
    number_of_weeks_at_1xweek: 0,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 3,
    progres_x_ray: 1,
    denne_roll: 0,
    foam_roller: 0,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "II/36/3",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 3,
    number_of_visits: 36,
    number_of_monts: 3,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 12,
    number_of_weeks_at_2xweek: 12,
    number_of_weeks_at_1xweek: 0,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 3,
    progres_x_ray: 1,
    denne_roll: 0,
    foam_roller: 0,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "II/24/1",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 1,
    number_of_visits: 36,
    number_of_monts: 3,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 0,
    number_of_weeks_at_2xweek: 12,
    number_of_weeks_at_1xweek: 0,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 3,
    progres_x_ray: 1,
    denne_roll: 0,
    foam_roller: 0,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "II/24/1",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 24,
    number_of_monts: 4,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 0,
    number_of_weeks_at_2xweek: 4,
    number_of_weeks_at_1xweek: 8,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 3,
    progres_x_ray: 1,
    denne_roll: 0,
    foam_roller: 0,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "CC/52",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 52,
    number_of_monts: 12,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 0,
    number_of_weeks_at_2xweek: 0,
    number_of_weeks_at_1xweek: 52,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 4,
    progres_x_ray: 1,
    denne_roll: 1,
    foam_roller: 1,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "CC/68",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 68,
    number_of_monts: 8,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 0,
    number_of_weeks_at_2xweek: 34,
    number_of_weeks_at_1xweek: 0,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 4,
    progres_x_ray: 1,
    denne_roll: 1,
    foam_roller: 1,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "CC/26",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 26,
    number_of_monts: 6,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 0,
    number_of_weeks_at_2xweek: 0,
    number_of_weeks_at_1xweek: 26,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 2,
    progres_x_ray: 1,
    denne_roll: 1,
    foam_roller: 1,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "CC/34",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 34,
    number_of_monts: 4,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 4,
    number_of_weeks_at_2xweek: 17,
    number_of_weeks_at_1xweek: 0,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 2,
    progres_x_ray: 1,
    denne_roll: 1,
    foam_roller: 1,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "W",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 52,
    number_of_monts: 12,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 0,
    number_of_weeks_at_2xweek: 0,
    number_of_weeks_at_1xweek: 52,
    number_of_weeks_at_eoweek: 0,
    progres_exam: 2,
    progres_x_ray: 1,
    denne_roll: 0,
    foam_roller: 0,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
  {
    name_of_prebuilt_care_plan: "M",
    stage_of_care: "Initial Intensive Care",
    name_of_patient: "text",
    stage_of_degeneration: 2,
    number_of_visits: 26,
    number_of_monts: 12,
    number_of_weeks_at_4xweek: 0,
    number_of_weeks_at_3xweek: 0,
    number_of_weeks_at_2xweek: 0,
    number_of_weeks_at_1xweek: 0,
    number_of_weeks_at_eoweek: 26,
    progres_exam: 2,
    progres_x_ray: 1,
    denne_roll: 0,
    foam_roller: 0,
    total_cost_of_care: 400,
    pay_in_full: 100,
    monthly: 50,
  },
];
